export const SET_POPUP_SHOW = 'SET_POPUP_SHOW';
export const SET_ZOOMIN_CONTENT = 'SET_ZOOMIN_CONTENT';
export const SET_PICKED_OUTFIT_DATE = 'SET_PICKED_OUTFIT_DATE';
export const INSERT_PICKED_CLOTH_ITEMS = 'INSERT_PICKED_CLOTH_ITEMS';
export const DELETE_PICKED_CLOTH_ITEMS = 'DELETE_PICKED_CLOTH_ITEMS';
export const INSERT_PUZZLE = 'INSERT_PUZZLE';